### PR TITLE
Refactoring, cleanup

### PR DESCRIPTION
**Pull request by kiner-shah**
PR for #4 
- Cleaned up classes a bit
- Removed typedefs.hpp
- Formatting
- Code improvements
- Fixed warnings

More refactoring is possible, will check that later. I need to understand code for that, so it would be helpful if you can add some comments.

### CODE REVIEW

**Comment by kiner-shah** [comment]
@Isembart can you please review this?

**Comment by Isembart** [comment]
I gave a quick glance due to lack of free time right now. I see you did some needed changes to the codebase :D
However i could build the project using my usual setup.
Compiler does not recognize sqrtf, powf & atan2

_f functions seems to be found when deleting std:: before them. 
Weird behaviour since the projects builds while using VS22 cmake generator.

I ran a github build action so you can see the logs

**Comment by kiner-shah** [comment]
> I ran a github build action so you can see the logs

Based on the logs of Github actions, I fixed few things. For test files, I originally didn't touch them, but since there was one error, I fixed that.

> Compiler does not recognize sqrtf, powf & atan2
> _f functions seems to be found when deleting std:: before them.

Can you please share error logs for the above?

**Comment by Isembart** [comment]
Can you check those math functions? Can you make it work on linux please?

**Comment by kiner-shah** [comment]
@Isembart I don't know why on GCC and Clang, std::powf, std::sqrtf are not recognized, they seem to work on MSVC, quite strange. I replaced them back to std::pow and std::sqrt. Now it should compile fine. Please check.

**Comment by Isembart** [comment]
"15

Up until C++11, powf was just a [Microsoft-ism](http://msdn.microsoft.com/en-us/library/dt5dakze%28v=vs.90%29.aspx). It did not appear in the ISO standard at all so is unlikely to be in XCode unless they were to adapt Microsoft's bizarre practices, something I would think unlikely.

pow, on the other hand, has been part of the C++ library for longer by virtue of the fact that it's in earlier iterations of the C library that is incorporated into C++ pre-11. Use that instead.

Since C++11, powf does appear in the ISO standard and is part of the std namespace.

Nevertheless, there are non-compliant implementations e.g., gcc libstdc++. More resources in this"

https://stackoverflow.com/questions/5483930/powf-is-not-a-member-of-std

I tried changing c++ standard in cmake file but it didn't help.

**Pull request merged**
